CREATE TABLE CARS (
    ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    PRODUCER VARCHAR(50),
	MODEL VARCHAR(50),
	SPZ VARCHAR(50),
	MANUFACTURED DATE,
	PRICE DECIMAL
 );

CREATE TABLE CUSTOMERS (
    ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(50),
	SURNAME VARCHAR(50),
	DRIVINGLICENSENUMBER INTEGER,
	IDENTIFICATIONCARDNUMBER INTEGER,
	DEBT DECIMAL
 );



CREATE TABLE ORDERS (
    ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    FROMO DATE,
    TOO DATE,
    CAR BIGINT, 
    CUSTOMER BIGINT
 );



INSERT INTO CARS (PRODUCER,MODEL,SPZ,MANUFACTURED,PRICE) VALUES 
	('Skoda','Fabia','1B0-1234','2010-05-12',1000),
	('VW','Golf','1B0-5678','2010-12-05',1000),
	('Skoda','Octavia','1B0-9012','2010-05-12',1000);

INSERT INTO CUSTOMERS (NAME,SURNAME,DRIVINGLICENSENUMBER,IDENTIFICATIONCARDNUMBER,DEBT) VALUES 
	('Lojzík','Vopička',1234,4321,1000),
	('Mařenka','Paklíčová',1235,4322,1001),
	('Jaroslav','Cimrman',1236,4323,1003);





